import { deepStrictEqual, strictEqual, throws } from 'node:assert/strict';
import { releaseFromGitHub, renderReleaseFile } from './sync-releases';

run('releaseFromGitHub maps GitHub release metadata to generated release facts', () => {
  deepStrictEqual(
    releaseFromGitHub(
      {
        tag_name: 'v1.2.3',
        published_at: '2026-06-24T12:34:56Z',
        html_url: 'https://github.com/juliopolycarpo/mangostudio/releases/tag/v1.2.3',
      },
      '2026-06-24T13:00:00.000Z'
    ),
    {
      version: 'v1.2.3',
      releaseDate: '2026-06-24',
      installCmd: 'bun add -g @mangostudio/cli',
      source: 'https://github.com/juliopolycarpo/mangostudio/releases/tag/v1.2.3',
      generatedAt: '2026-06-24T13:00:00.000Z',
    }
  );
});

run('releaseFromGitHub normalizes unprefixed tags', () => {
  strictEqual(
    releaseFromGitHub({
      tag_name: '1.2.3',
      published_at: '2026-06-24T12:34:56Z',
      html_url: 'https://github.com/juliopolycarpo/mangostudio/releases/tag/v1.2.3',
    }).version,
    'v1.2.3'
  );
});

run('releaseFromGitHub rejects invalid metadata', () => {
  throws(
    () =>
      releaseFromGitHub({
        tag_name: '',
        published_at: 'not-a-date',
        html_url: 'not-a-url',
      }),
    /tag_name/
  );
});

run('renderReleaseFile renders deterministic TypeScript', () => {
  strictEqual(
    renderReleaseFile({
      version: 'v1.2.3',
      releaseDate: '2026-06-24',
      installCmd: 'bun add -g @mangostudio/cli',
      source: 'https://github.com/juliopolycarpo/mangostudio/releases/tag/v1.2.3',
      generatedAt: '2026-06-24T13:00:00.000Z',
    }),
    `// AUTO-GENERATED by scripts/sync-releases.ts - edit the generator, not this file.
export interface GeneratedRelease {
  version: string;
  releaseDate: string;
  installCmd: string;
  source: string;
  generatedAt: string;
}

export const RELEASE: GeneratedRelease = {
  version: "v1.2.3",
  releaseDate: "2026-06-24",
  installCmd: "bun add -g @mangostudio/cli",
  source: "https://github.com/juliopolycarpo/mangostudio/releases/tag/v1.2.3",
  generatedAt: "2026-06-24T13:00:00.000Z"
};
`
  );
});

function run(name: string, fn: () => void): void {
  try {
    fn();
    process.stdout.write(`[ok] ${name}\n`);
  } catch (error) {
    process.stderr.write(`[fail] ${name}\n`);
    throw error;
  }
}
