import { execFile } from 'node:child_process';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, posix, relative, resolve, sep } from 'node:path';
import { promisify } from 'node:util';

import type { Lang } from '../src/i18n/types';

const execFileAsync = promisify(execFile);

const DEFAULT_SOURCE_DIR = join(process.cwd(), '..', 'mangostudio');
const GENERATED_CONTENT_DIR = join('src', 'content', 'docs');
const GENERATED_MANIFEST_PATH = join('src', 'data', 'docs.generated.ts');
const SOURCE_REPO = 'https://github.com/juliopolycarpo/mangostudio';
const AUTO_GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/sync-docs.ts - edit the generator, not this file.';

type DocGroupId =
  | 'getting-started'
  | 'guides'
  | 'features'
  | 'providers'
  | 'architecture'
  | 'reference'
  | 'operations';

interface SourceDocDefinition {
  slug: string;
  groupId: DocGroupId;
  order: number;
  sidebarLabel?: Partial<Record<Lang, string>>;
  sources: Record<Lang, string>;
}

interface GeneratedDocItem {
  slug: string;
  title: string;
  sidebarLabel: string;
  sourcePath: string;
  sourceUrl: string;
  groupId: DocGroupId;
  groupTitle: string;
  order: number;
}

interface GeneratedDocGroup {
  id: DocGroupId;
  title: string;
  items: GeneratedDocItem[];
}

export interface SyncDocsOptions {
  sourceDir?: string;
  repoRoot?: string;
  check?: boolean;
  sourceCommit?: string;
}

export interface SyncDocsResult {
  sourceCommit: string;
  docs: Record<Lang, GeneratedDocGroup[]>;
}

const GROUP_TITLES: Record<Lang, Record<DocGroupId, string>> = {
  pt: {
    'getting-started': 'Começando',
    guides: 'Guias',
    features: 'Recursos',
    providers: 'Provedores',
    architecture: 'Arquitetura',
    reference: 'Referência',
    operations: 'Operações',
  },
  en: {
    'getting-started': 'Getting Started',
    guides: 'Guides',
    features: 'Features',
    providers: 'Providers',
    architecture: 'Architecture',
    reference: 'Reference',
    operations: 'Operations',
  },
};

const GROUP_ORDER: Record<DocGroupId, number> = {
  'getting-started': 10,
  guides: 20,
  features: 30,
  providers: 40,
  architecture: 50,
  reference: 60,
  operations: 70,
};

const DOC_ORDER: Record<string, number> = {
  quickstart: 10,
  'guides/contributing': 10,
  'guides/contributor-quickstart': 20,
  'features/settings': 10,
  'features/tools': 20,
  'features/attachments': 30,
  'features/image-generation': 40,
  'providers/development': 10,
  'providers/deepseek': 20,
  'architecture/overview': 10,
  'architecture/streaming': 20,
  'architecture/continuation': 30,
  'architecture/context-compaction': 40,
  'architecture/i18n': 50,
  'reference/cli': 10,
  'reference/api': 20,
  'reference/testing': 30,
  'reference/tooling': 40,
  'reference/agent-playbooks': 50,
  'reference/releasing': 60,
  'operations/deployment': 10,
  'operations/security': 20,
};

const SPECIAL_DOCS: SourceDocDefinition[] = [
  {
    slug: 'quickstart',
    groupId: 'getting-started',
    order: DOC_ORDER.quickstart,
    sidebarLabel: { pt: 'Início rápido', en: 'Quickstart' },
    sources: { pt: 'docs/pt-br/README.md', en: 'README.md' },
  },
  {
    slug: 'guides/contributing',
    groupId: 'guides',
    order: DOC_ORDER['guides/contributing'],
    sources: { pt: 'docs/pt-br/CONTRIBUTING.md', en: '.github/CONTRIBUTING.md' },
  },
  {
    slug: 'operations/security',
    groupId: 'operations',
    order: DOC_ORDER['operations/security'],
    sources: { pt: 'docs/pt-br/operations/security.md', en: '.github/SECURITY.md' },
  },
];

export async function syncDocs(options: SyncDocsOptions = {}): Promise<SyncDocsResult> {
  const repoRoot = resolve(options.repoRoot ?? process.cwd());
  const sourceDir = resolve(options.sourceDir ?? DEFAULT_SOURCE_DIR);
  const sourceCommit = options.sourceCommit ?? (await readSourceCommit(sourceDir));
  const definitions = await collectDocDefinitions(sourceDir);
  const sourcePathMap = createSourcePathMap(definitions);
  const docs = createEmptyDocsNav();
  const generatedFiles = new Map<string, string>();

  for (const definition of definitions) {
    for (const lang of ['pt', 'en'] as const) {
      const sourcePath = definition.sources[lang];
      const sourceFile = join(sourceDir, sourcePath);
      const original = await readFile(sourceFile, 'utf8');
      const cleaned = sanitizeMarkdown(original);
      const linked = rewriteMarkdownLinks(cleaned, {
        lang,
        sourcePath,
        sourceCommit,
        sourcePathMap,
      });
      const title = extractTitle(linked);
      const sidebarLabel = definition.sidebarLabel?.[lang] ?? title;
      const sourceUrl = sourceBlobUrl(sourceCommit, sourcePath);
      const groupTitle = GROUP_TITLES[lang][definition.groupId];
      const item: GeneratedDocItem = {
        slug: definition.slug,
        title,
        sidebarLabel,
        sourcePath,
        sourceUrl,
        groupId: definition.groupId,
        groupTitle,
        order: definition.order,
      };
      const targetPath = join(repoRoot, GENERATED_CONTENT_DIR, lang, `${definition.slug}.md`);

      docs[lang].find((group) => group.id === definition.groupId)?.items.push(item);
      generatedFiles.set(
        targetPath,
        renderContentFile(linked, {
          ...item,
          lang,
          sourceCommit,
        })
      );
    }
  }

  sortDocsNav(docs);
  const manifest = renderManifest({ sourceCommit, docs });
  generatedFiles.set(join(repoRoot, GENERATED_MANIFEST_PATH), manifest);

  if (options.check) {
    await assertGeneratedFilesCurrent(repoRoot, generatedFiles);
  } else {
    await writeGeneratedFiles(repoRoot, generatedFiles);
  }

  return { sourceCommit, docs };
}

export async function collectDocDefinitions(sourceDir: string): Promise<SourceDocDefinition[]> {
  const definitions = [...SPECIAL_DOCS];
  const docsDir = join(sourceDir, 'docs');
  const docsPaths = await collectMarkdownFiles(docsDir);

  for (const docsPath of docsPaths) {
    if (docsPath === 'README.md' || docsPath.startsWith('pt-br/')) {
      continue;
    }

    const slug = stripMarkdownExtension(docsPath);

    if (definitions.some((definition) => definition.slug === slug)) {
      continue;
    }

    const groupId = groupIdForSlug(slug);
    const ptSource = `docs/pt-br/${docsPath}`;
    const enSource = `docs/${docsPath}`;

    await assertReadable(
      join(sourceDir, ptSource),
      `Missing Portuguese docs mirror for ${enSource}`
    );

    definitions.push({
      slug,
      groupId,
      order: DOC_ORDER[slug] ?? 100,
      sources: { pt: ptSource, en: enSource },
    });
  }

  return definitions.sort((a, b) => {
    const groupDelta = GROUP_ORDER[a.groupId] - GROUP_ORDER[b.groupId];
    return groupDelta || a.order - b.order || a.slug.localeCompare(b.slug);
  });
}

export function sanitizeMarkdown(input: string): string {
  return input
    .replace(
      /<div\b[^>]*>\s*<img\b[^>]*\bsrc=["'](?:https?:)?\/\/[^"']+["'][\s\S]*?<\/div>\s*/gi,
      ''
    )
    .replace(/\[!\[([^\]]*)\]\((?:https?:)?\/\/[^)]+\)\]\(([^)]+)\)/g, '[$1]($2)')
    .replace(/!\[([^\]]*)\]\((?:https?:)?\/\/[^)]+\)/g, '$1')
    .replace(/<img\b[^>]*\bsrc=["'](?:https?:)?\/\/[^"']+["'][^>]*>\s*/gi, '');
}

export function rewriteMarkdownLinks(
  input: string,
  context: {
    lang: Lang;
    sourcePath: string;
    sourceCommit: string;
    sourcePathMap: Map<string, { lang: Lang; slug: string }>;
  }
): string {
  const rewrite = (href: string): string =>
    rewriteHref(href, {
      sourcePath: context.sourcePath,
      sourceCommit: context.sourceCommit,
      sourcePathMap: context.sourcePathMap,
    });

  return input
    .replace(/(?<!!)\[([^\]\n]+)\]\(([^)\s]+)\)/g, (_match, label: string, href: string) => {
      return `[${label}](${rewrite(href)})`;
    })
    .replace(/\bhref="([^"]+)"/g, (_match, href: string) => `href="${rewrite(href)}"`);
}

export function renderManifest(input: {
  sourceCommit: string;
  docs: Record<Lang, GeneratedDocGroup[]>;
}): string {
  const docsBySlug = Object.fromEntries(
    (['pt', 'en'] as const).map((lang) => [
      lang,
      Object.fromEntries(
        input.docs[lang].flatMap((group) =>
          group.items.map((item) => [item.slug, { ...item, groupTitle: group.title }])
        )
      ),
    ])
  );

  return `${AUTO_GENERATED_HEADER}
import type { Lang } from '@/i18n/types';

export type DocGroupId = ${Object.keys(GROUP_ORDER)
    .map((group) => JSON.stringify(group))
    .join(' | ')};

export interface GeneratedDocNavItem {
  slug: string;
  title: string;
  sidebarLabel: string;
  sourcePath: string;
  sourceUrl: string;
  groupId: DocGroupId;
  groupTitle: string;
  order: number;
}

export interface GeneratedDocNavGroup {
  id: DocGroupId;
  title: string;
  items: GeneratedDocNavItem[];
}

export const DOCS_DEFAULT_SLUG = 'quickstart';

export const DOCS_SOURCE = {
  repo: ${JSON.stringify(SOURCE_REPO)},
  commit: ${JSON.stringify(input.sourceCommit)}
} as const;

export const DOCS_NAV = ${JSON.stringify(input.docs, null, 2)} as const satisfies Record<Lang, readonly GeneratedDocNavGroup[]>;

export const DOCS_BY_SLUG = ${JSON.stringify(docsBySlug, null, 2)} as const satisfies Record<Lang, Record<string, GeneratedDocNavItem>>;
`;
}

function createEmptyDocsNav(): Record<Lang, GeneratedDocGroup[]> {
  return {
    pt: createEmptyDocsGroups('pt'),
    en: createEmptyDocsGroups('en'),
  };
}

function createEmptyDocsGroups(lang: Lang): GeneratedDocGroup[] {
  return (Object.keys(GROUP_ORDER) as DocGroupId[]).map((id) => ({
    id,
    title: GROUP_TITLES[lang][id],
    items: [],
  }));
}

function sortDocsNav(docs: Record<Lang, GeneratedDocGroup[]>): void {
  for (const lang of ['pt', 'en'] as const) {
    docs[lang].sort((a, b) => GROUP_ORDER[a.id] - GROUP_ORDER[b.id]);
    for (const group of docs[lang]) {
      group.items.sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
    }
  }
}

function createSourcePathMap(
  definitions: SourceDocDefinition[]
): Map<string, { lang: Lang; slug: string }> {
  const map = new Map<string, { lang: Lang; slug: string }>();

  for (const definition of definitions) {
    for (const lang of ['pt', 'en'] as const) {
      map.set(definition.sources[lang], { lang, slug: definition.slug });
    }
  }

  return map;
}

function rewriteHref(
  href: string,
  context: {
    sourcePath: string;
    sourceCommit: string;
    sourcePathMap: Map<string, { lang: Lang; slug: string }>;
  }
): string {
  if (href.startsWith('#') || /^(?:https?:\/\/|mailto:|tel:)/i.test(href)) {
    return href;
  }

  const [pathPart = '', suffix = ''] = splitHrefSuffix(href);

  if (!pathPart.endsWith('.md')) {
    return href;
  }

  const targetPath = normalizeSourcePath(posix.join(posix.dirname(context.sourcePath), pathPart));
  const targetDoc = context.sourcePathMap.get(targetPath);

  if (targetDoc) {
    const prefix = targetDoc.lang === 'en' ? '/en' : '';
    return `${prefix}/docs/${targetDoc.slug}${suffix}`;
  }

  return `${sourceBlobUrl(context.sourceCommit, targetPath)}${suffix}`;
}

function splitHrefSuffix(href: string): [string, string] {
  const markerIndex = href.search(/[?#]/);

  if (markerIndex === -1) {
    return [href, ''];
  }

  return [href.slice(0, markerIndex), href.slice(markerIndex)];
}

function normalizeSourcePath(path: string): string {
  return posix.normalize(path).replace(/^\.\//, '');
}

function groupIdForSlug(slug: string): DocGroupId {
  const [group] = slug.split('/');

  switch (group) {
    case 'architecture':
    case 'features':
    case 'providers':
    case 'reference':
    case 'operations':
    case 'guides':
      return group;
    default:
      return 'getting-started';
  }
}

function stripMarkdownExtension(path: string): string {
  return path.replace(/\.md$/i, '');
}

function extractTitle(markdown: string): string {
  const title = /^#\s+(.+)$/m.exec(markdown)?.[1]?.trim();

  if (!title) {
    throw new Error('Synced docs must include a top-level heading.');
  }

  return title
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

function renderContentFile(
  markdown: string,
  data: GeneratedDocItem & { lang: Lang; sourceCommit: string }
): string {
  return `---
title: ${JSON.stringify(data.title)}
sidebarLabel: ${JSON.stringify(data.sidebarLabel)}
lang: ${JSON.stringify(data.lang)}
slug: ${JSON.stringify(data.slug)}
groupId: ${JSON.stringify(data.groupId)}
groupTitle: ${JSON.stringify(data.groupTitle)}
order: ${data.order}
sourcePath: ${JSON.stringify(data.sourcePath)}
sourceUrl: ${JSON.stringify(data.sourceUrl)}
sourceCommit: ${JSON.stringify(data.sourceCommit)}
---

${markdown.trim()}
`;
}

async function collectMarkdownFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  await collectMarkdownFilesRecursive(rootDir, rootDir, files);
  return files.sort();
}

async function collectMarkdownFilesRecursive(
  rootDir: string,
  currentDir: string,
  files: string[]
): Promise<void> {
  const entries = await readdir(currentDir, { withFileTypes: true });

  for (const entry of entries) {
    const path = join(currentDir, entry.name);

    if (entry.isDirectory()) {
      await collectMarkdownFilesRecursive(rootDir, path, files);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      files.push(toPosixPath(relative(rootDir, path)));
    }
  }
}

async function writeGeneratedFiles(repoRoot: string, files: Map<string, string>): Promise<void> {
  await rm(join(repoRoot, GENERATED_CONTENT_DIR), { force: true, recursive: true });

  for (const [filePath, text] of files) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, text, 'utf8');
  }
}

async function assertGeneratedFilesCurrent(
  repoRoot: string,
  files: Map<string, string>
): Promise<void> {
  const errors: string[] = [];

  for (const [filePath, expected] of files) {
    let actual = '';

    try {
      actual = await readFile(filePath, 'utf8');
    } catch {
      errors.push(`${toRepoRelative(repoRoot, filePath)} is missing.`);
      continue;
    }

    if (actual !== expected) {
      errors.push(`${toRepoRelative(repoRoot, filePath)} is out of sync.`);
    }
  }

  if (errors.length > 0) {
    throw new Error(`Docs sync check failed:\n${errors.join('\n')}`);
  }
}

async function readSourceCommit(sourceDir: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync('git', ['-C', sourceDir, 'rev-parse', 'HEAD']);
    return stdout.trim();
  } catch {
    return 'unknown';
  }
}

async function assertReadable(path: string, message: string): Promise<void> {
  try {
    await readFile(path, 'utf8');
  } catch {
    throw new Error(message);
  }
}

function sourceBlobUrl(commit: string, sourcePath: string): string {
  return `${SOURCE_REPO}/blob/${commit}/${sourcePath}`;
}

function toPosixPath(path: string): string {
  return sep === '/' ? path : path.split(sep).join('/');
}

function toRepoRelative(repoRoot: string, filePath: string): string {
  return toPosixPath(relative(repoRoot, filePath));
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const sourceIndex = args.indexOf('--source');
  const check = args.includes('--check');
  const sourceDir = sourceIndex >= 0 ? args[sourceIndex + 1] : undefined;

  if (sourceIndex >= 0 && !sourceDir) {
    throw new Error('Usage: bun ./scripts/sync-docs.ts [--source <path>] [--check]');
  }

  await syncDocs({ sourceDir, check });
}
