import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export interface ReleaseInput {
  tag_name: string;
  published_at: string;
  html_url: string;
}

export interface GeneratedRelease {
  version: string;
  releaseDate: string;
  installCmd: string;
  source: string;
}

const GENERATED_PATH = join(process.cwd(), 'src', 'data', 'releases.generated.ts');

export function releaseFromGitHub(input: ReleaseInput): GeneratedRelease {
  validateReleaseInput(input);

  return {
    version: normalizeVersion(input.tag_name),
    releaseDate: input.published_at.slice(0, 10),
    installCmd: 'bun add -g @mangostudio/cli',
    source: input.html_url,
  };
}

export function renderReleaseFile(release: GeneratedRelease): string {
  return `${AUTO_GENERATED_HEADER}
export interface GeneratedRelease {
  version: string;
  releaseDate: string;
  installCmd: string;
  source: string;
}

export const RELEASE: GeneratedRelease = ${JSON.stringify(release, null, 2).replace(/"([^"]+)":/g, '$1:')};
`;
}

export async function writeReleaseFile(
  input: ReleaseInput,
  outputPath = GENERATED_PATH
): Promise<void> {
  const release = releaseFromGitHub(input);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderReleaseFile(release), 'utf8');
}

const AUTO_GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/sync-releases.ts - edit the generator, not this file.';

if (import.meta.main) {
  const inputPath = process.argv[2];

  if (!inputPath) {
    throw new Error('Usage: bun ./scripts/sync-releases.ts <release.json>');
  }

  const parsed = JSON.parse(await readFile(inputPath, 'utf8'));
  await writeReleaseFile(parsed);
}

function validateReleaseInput(input: ReleaseInput): void {
  if (!isRecord(input)) {
    throw new Error('Release metadata must be an object.');
  }

  if (typeof input.tag_name !== 'string' || input.tag_name.trim() === '') {
    throw new Error('Release metadata must include tag_name.');
  }

  if (typeof input.published_at !== 'string' || Number.isNaN(Date.parse(input.published_at))) {
    throw new Error('Release metadata must include a valid published_at timestamp.');
  }

  if (typeof input.html_url !== 'string' || !URL.canParse(input.html_url)) {
    throw new Error('Release metadata must include a valid html_url.');
  }
}

function normalizeVersion(tagName: string): string {
  return tagName.startsWith('v') ? tagName : `v${tagName}`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
