// AUTO-GENERATED by scripts/sync-docs.ts - edit the generator, not this file.
import type { Lang } from '@/i18n/types';

export type DocGroupId =
  | 'getting-started'
  | 'guides'
  | 'features'
  | 'providers'
  | 'architecture'
  | 'reference'
  | 'operations';

export interface GeneratedDocNavItem {
  slug: string;
  title: string;
  sidebarLabel: string;
  sourcePath: string;
  sourceUrl: string;
  groupId: DocGroupId;
  groupTitle: string;
  order: number;
}

export interface GeneratedDocNavGroup {
  id: DocGroupId;
  title: string;
  items: GeneratedDocNavItem[];
}

export const DOCS_DEFAULT_SLUG = 'quickstart';

export const DOCS_SOURCE = {
  repo: 'https://github.com/juliopolycarpo/mangostudio',
  commit: 'c8a260ecd3cf98c5fb630b756a93afe762cb2af8',
} as const;

export const DOCS_NAV = {
  pt: [
    {
      id: 'getting-started',
      title: 'Começando',
      items: [
        {
          slug: 'quickstart',
          title: 'MangoStudio',
          sidebarLabel: 'Início rápido',
          sourcePath: 'docs/pt-br/README.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/README.md',
          groupId: 'getting-started',
          groupTitle: 'Começando',
          order: 10,
        },
      ],
    },
    {
      id: 'guides',
      title: 'Guias',
      items: [
        {
          slug: 'guides/contributing',
          title: 'Contribuindo com o MangoStudio',
          sidebarLabel: 'Contribuindo com o MangoStudio',
          sourcePath: 'docs/pt-br/CONTRIBUTING.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/CONTRIBUTING.md',
          groupId: 'guides',
          groupTitle: 'Guias',
          order: 10,
        },
        {
          slug: 'guides/contributor-quickstart',
          title: 'Início Rápido Para Contribuidores',
          sidebarLabel: 'Início Rápido Para Contribuidores',
          sourcePath: 'docs/pt-br/guides/contributor-quickstart.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/guides/contributor-quickstart.md',
          groupId: 'guides',
          groupTitle: 'Guias',
          order: 20,
        },
      ],
    },
    {
      id: 'features',
      title: 'Recursos',
      items: [
        {
          slug: 'features/settings',
          title: 'Arquitetura De Settings',
          sidebarLabel: 'Arquitetura De Settings',
          sourcePath: 'docs/pt-br/features/settings.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/settings.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 10,
        },
        {
          slug: 'features/tools',
          title: 'Sistema De Tools',
          sidebarLabel: 'Sistema De Tools',
          sourcePath: 'docs/pt-br/features/tools.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/tools.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 20,
        },
        {
          slug: 'features/attachments',
          title: 'Attachments',
          sidebarLabel: 'Attachments',
          sourcePath: 'docs/pt-br/features/attachments.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/attachments.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 30,
        },
        {
          slug: 'features/image-generation',
          title: 'Geração De Imagem',
          sidebarLabel: 'Geração De Imagem',
          sourcePath: 'docs/pt-br/features/image-generation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/image-generation.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 40,
        },
      ],
    },
    {
      id: 'providers',
      title: 'Provedores',
      items: [
        {
          slug: 'providers/development',
          title: 'Guia De Desenvolvimento De Provedores',
          sidebarLabel: 'Guia De Desenvolvimento De Provedores',
          sourcePath: 'docs/pt-br/providers/development.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/providers/development.md',
          groupId: 'providers',
          groupTitle: 'Provedores',
          order: 10,
        },
        {
          slug: 'providers/deepseek',
          title: 'Provedor DeepSeek',
          sidebarLabel: 'Provedor DeepSeek',
          sourcePath: 'docs/pt-br/providers/deepseek.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/providers/deepseek.md',
          groupId: 'providers',
          groupTitle: 'Provedores',
          order: 20,
        },
      ],
    },
    {
      id: 'architecture',
      title: 'Arquitetura',
      items: [
        {
          slug: 'architecture/overview',
          title: 'Visão Geral Da Arquitetura',
          sidebarLabel: 'Visão Geral Da Arquitetura',
          sourcePath: 'docs/pt-br/architecture/overview.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/overview.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 10,
        },
        {
          slug: 'architecture/streaming',
          title: 'Arquitetura De Streaming',
          sidebarLabel: 'Arquitetura De Streaming',
          sourcePath: 'docs/pt-br/architecture/streaming.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/streaming.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 20,
        },
        {
          slug: 'architecture/continuation',
          title: 'Arquitetura De Continuação',
          sidebarLabel: 'Arquitetura De Continuação',
          sourcePath: 'docs/pt-br/architecture/continuation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/continuation.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 30,
        },
        {
          slug: 'architecture/context-compaction',
          title: 'Compactação De Contexto',
          sidebarLabel: 'Compactação De Contexto',
          sourcePath: 'docs/pt-br/architecture/context-compaction.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/context-compaction.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 40,
        },
        {
          slug: 'architecture/i18n',
          title: 'Internacionalização (i18n)',
          sidebarLabel: 'Internacionalização (i18n)',
          sourcePath: 'docs/pt-br/architecture/i18n.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/i18n.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 50,
        },
      ],
    },
    {
      id: 'reference',
      title: 'Referência',
      items: [
        {
          slug: 'reference/cli',
          title: 'Referência da CLI',
          sidebarLabel: 'Referência da CLI',
          sourcePath: 'docs/pt-br/reference/cli.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/cli.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 10,
        },
        {
          slug: 'reference/api',
          title: 'Referência Da API',
          sidebarLabel: 'Referência Da API',
          sourcePath: 'docs/pt-br/reference/api.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/api.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 20,
        },
        {
          slug: 'reference/testing',
          title: 'Estratégia De Testes',
          sidebarLabel: 'Estratégia De Testes',
          sourcePath: 'docs/pt-br/reference/testing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/testing.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 30,
        },
        {
          slug: 'reference/tooling',
          title: 'Ferramentas',
          sidebarLabel: 'Ferramentas',
          sourcePath: 'docs/pt-br/reference/tooling.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/tooling.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 40,
        },
        {
          slug: 'reference/agent-playbooks',
          title: 'Playbooks De Agentes',
          sidebarLabel: 'Playbooks De Agentes',
          sourcePath: 'docs/pt-br/reference/agent-playbooks.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/agent-playbooks.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 50,
        },
        {
          slug: 'reference/releasing',
          title: 'Releases',
          sidebarLabel: 'Releases',
          sourcePath: 'docs/pt-br/reference/releasing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/releasing.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 60,
        },
      ],
    },
    {
      id: 'operations',
      title: 'Operações',
      items: [
        {
          slug: 'operations/deployment',
          title: 'Deploy',
          sidebarLabel: 'Deploy',
          sourcePath: 'docs/pt-br/operations/deployment.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/operations/deployment.md',
          groupId: 'operations',
          groupTitle: 'Operações',
          order: 10,
        },
        {
          slug: 'operations/security',
          title: 'Política De Segurança',
          sidebarLabel: 'Política De Segurança',
          sourcePath: 'docs/pt-br/operations/security.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/operations/security.md',
          groupId: 'operations',
          groupTitle: 'Operações',
          order: 20,
        },
      ],
    },
  ],
  en: [
    {
      id: 'getting-started',
      title: 'Getting Started',
      items: [
        {
          slug: 'quickstart',
          title: 'MangoStudio',
          sidebarLabel: 'Quickstart',
          sourcePath: 'README.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/README.md',
          groupId: 'getting-started',
          groupTitle: 'Getting Started',
          order: 10,
        },
      ],
    },
    {
      id: 'guides',
      title: 'Guides',
      items: [
        {
          slug: 'guides/contributing',
          title: 'Contributing to MangoStudio',
          sidebarLabel: 'Contributing to MangoStudio',
          sourcePath: '.github/CONTRIBUTING.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/.github/CONTRIBUTING.md',
          groupId: 'guides',
          groupTitle: 'Guides',
          order: 10,
        },
        {
          slug: 'guides/contributor-quickstart',
          title: 'Contributor Quickstart',
          sidebarLabel: 'Contributor Quickstart',
          sourcePath: 'docs/guides/contributor-quickstart.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/guides/contributor-quickstart.md',
          groupId: 'guides',
          groupTitle: 'Guides',
          order: 20,
        },
      ],
    },
    {
      id: 'features',
      title: 'Features',
      items: [
        {
          slug: 'features/settings',
          title: 'Settings Architecture',
          sidebarLabel: 'Settings Architecture',
          sourcePath: 'docs/features/settings.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/settings.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 10,
        },
        {
          slug: 'features/tools',
          title: 'Tools System',
          sidebarLabel: 'Tools System',
          sourcePath: 'docs/features/tools.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/tools.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 20,
        },
        {
          slug: 'features/attachments',
          title: 'Attachments',
          sidebarLabel: 'Attachments',
          sourcePath: 'docs/features/attachments.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/attachments.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 30,
        },
        {
          slug: 'features/image-generation',
          title: 'Image Generation',
          sidebarLabel: 'Image Generation',
          sourcePath: 'docs/features/image-generation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/image-generation.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 40,
        },
      ],
    },
    {
      id: 'providers',
      title: 'Providers',
      items: [
        {
          slug: 'providers/development',
          title: 'Provider Development Guide',
          sidebarLabel: 'Provider Development Guide',
          sourcePath: 'docs/providers/development.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/providers/development.md',
          groupId: 'providers',
          groupTitle: 'Providers',
          order: 10,
        },
        {
          slug: 'providers/deepseek',
          title: 'DeepSeek Provider',
          sidebarLabel: 'DeepSeek Provider',
          sourcePath: 'docs/providers/deepseek.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/providers/deepseek.md',
          groupId: 'providers',
          groupTitle: 'Providers',
          order: 20,
        },
      ],
    },
    {
      id: 'architecture',
      title: 'Architecture',
      items: [
        {
          slug: 'architecture/overview',
          title: 'Architecture Overview',
          sidebarLabel: 'Architecture Overview',
          sourcePath: 'docs/architecture/overview.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/overview.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 10,
        },
        {
          slug: 'architecture/streaming',
          title: 'Streaming Architecture',
          sidebarLabel: 'Streaming Architecture',
          sourcePath: 'docs/architecture/streaming.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/streaming.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 20,
        },
        {
          slug: 'architecture/continuation',
          title: 'Continuation Architecture',
          sidebarLabel: 'Continuation Architecture',
          sourcePath: 'docs/architecture/continuation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/continuation.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 30,
        },
        {
          slug: 'architecture/context-compaction',
          title: 'Context Compaction',
          sidebarLabel: 'Context Compaction',
          sourcePath: 'docs/architecture/context-compaction.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/context-compaction.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 40,
        },
        {
          slug: 'architecture/i18n',
          title: 'Internationalization (i18n)',
          sidebarLabel: 'Internationalization (i18n)',
          sourcePath: 'docs/architecture/i18n.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/i18n.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 50,
        },
      ],
    },
    {
      id: 'reference',
      title: 'Reference',
      items: [
        {
          slug: 'reference/cli',
          title: 'CLI Reference',
          sidebarLabel: 'CLI Reference',
          sourcePath: 'docs/reference/cli.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/cli.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 10,
        },
        {
          slug: 'reference/api',
          title: 'API Reference',
          sidebarLabel: 'API Reference',
          sourcePath: 'docs/reference/api.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/api.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 20,
        },
        {
          slug: 'reference/testing',
          title: 'Testing Strategy',
          sidebarLabel: 'Testing Strategy',
          sourcePath: 'docs/reference/testing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/testing.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 30,
        },
        {
          slug: 'reference/tooling',
          title: 'Tooling',
          sidebarLabel: 'Tooling',
          sourcePath: 'docs/reference/tooling.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/tooling.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 40,
        },
        {
          slug: 'reference/agent-playbooks',
          title: 'Agent Playbooks',
          sidebarLabel: 'Agent Playbooks',
          sourcePath: 'docs/reference/agent-playbooks.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/agent-playbooks.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 50,
        },
        {
          slug: 'reference/releasing',
          title: 'Releasing',
          sidebarLabel: 'Releasing',
          sourcePath: 'docs/reference/releasing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/releasing.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 60,
        },
      ],
    },
    {
      id: 'operations',
      title: 'Operations',
      items: [
        {
          slug: 'operations/deployment',
          title: 'Deployment',
          sidebarLabel: 'Deployment',
          sourcePath: 'docs/operations/deployment.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/operations/deployment.md',
          groupId: 'operations',
          groupTitle: 'Operations',
          order: 10,
        },
        {
          slug: 'operations/security',
          title: 'Security Policy',
          sidebarLabel: 'Security Policy',
          sourcePath: '.github/SECURITY.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/.github/SECURITY.md',
          groupId: 'operations',
          groupTitle: 'Operations',
          order: 20,
        },
      ],
    },
  ],
} as const satisfies Record<Lang, readonly GeneratedDocNavGroup[]>;

export const DOCS_BY_SLUG = {
  pt: {
    quickstart: {
      slug: 'quickstart',
      title: 'MangoStudio',
      sidebarLabel: 'Início rápido',
      sourcePath: 'docs/pt-br/README.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/README.md',
      groupId: 'getting-started',
      groupTitle: 'Começando',
      order: 10,
    },
    'guides/contributing': {
      slug: 'guides/contributing',
      title: 'Contribuindo com o MangoStudio',
      sidebarLabel: 'Contribuindo com o MangoStudio',
      sourcePath: 'docs/pt-br/CONTRIBUTING.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/CONTRIBUTING.md',
      groupId: 'guides',
      groupTitle: 'Guias',
      order: 10,
    },
    'guides/contributor-quickstart': {
      slug: 'guides/contributor-quickstart',
      title: 'Início Rápido Para Contribuidores',
      sidebarLabel: 'Início Rápido Para Contribuidores',
      sourcePath: 'docs/pt-br/guides/contributor-quickstart.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/guides/contributor-quickstart.md',
      groupId: 'guides',
      groupTitle: 'Guias',
      order: 20,
    },
    'features/settings': {
      slug: 'features/settings',
      title: 'Arquitetura De Settings',
      sidebarLabel: 'Arquitetura De Settings',
      sourcePath: 'docs/pt-br/features/settings.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/settings.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 10,
    },
    'features/tools': {
      slug: 'features/tools',
      title: 'Sistema De Tools',
      sidebarLabel: 'Sistema De Tools',
      sourcePath: 'docs/pt-br/features/tools.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/tools.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 20,
    },
    'features/attachments': {
      slug: 'features/attachments',
      title: 'Attachments',
      sidebarLabel: 'Attachments',
      sourcePath: 'docs/pt-br/features/attachments.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/attachments.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 30,
    },
    'features/image-generation': {
      slug: 'features/image-generation',
      title: 'Geração De Imagem',
      sidebarLabel: 'Geração De Imagem',
      sourcePath: 'docs/pt-br/features/image-generation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/features/image-generation.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 40,
    },
    'providers/development': {
      slug: 'providers/development',
      title: 'Guia De Desenvolvimento De Provedores',
      sidebarLabel: 'Guia De Desenvolvimento De Provedores',
      sourcePath: 'docs/pt-br/providers/development.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/providers/development.md',
      groupId: 'providers',
      groupTitle: 'Provedores',
      order: 10,
    },
    'providers/deepseek': {
      slug: 'providers/deepseek',
      title: 'Provedor DeepSeek',
      sidebarLabel: 'Provedor DeepSeek',
      sourcePath: 'docs/pt-br/providers/deepseek.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/providers/deepseek.md',
      groupId: 'providers',
      groupTitle: 'Provedores',
      order: 20,
    },
    'architecture/overview': {
      slug: 'architecture/overview',
      title: 'Visão Geral Da Arquitetura',
      sidebarLabel: 'Visão Geral Da Arquitetura',
      sourcePath: 'docs/pt-br/architecture/overview.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/overview.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 10,
    },
    'architecture/streaming': {
      slug: 'architecture/streaming',
      title: 'Arquitetura De Streaming',
      sidebarLabel: 'Arquitetura De Streaming',
      sourcePath: 'docs/pt-br/architecture/streaming.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/streaming.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 20,
    },
    'architecture/continuation': {
      slug: 'architecture/continuation',
      title: 'Arquitetura De Continuação',
      sidebarLabel: 'Arquitetura De Continuação',
      sourcePath: 'docs/pt-br/architecture/continuation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/continuation.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 30,
    },
    'architecture/context-compaction': {
      slug: 'architecture/context-compaction',
      title: 'Compactação De Contexto',
      sidebarLabel: 'Compactação De Contexto',
      sourcePath: 'docs/pt-br/architecture/context-compaction.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/context-compaction.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 40,
    },
    'architecture/i18n': {
      slug: 'architecture/i18n',
      title: 'Internacionalização (i18n)',
      sidebarLabel: 'Internacionalização (i18n)',
      sourcePath: 'docs/pt-br/architecture/i18n.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/architecture/i18n.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 50,
    },
    'reference/cli': {
      slug: 'reference/cli',
      title: 'Referência da CLI',
      sidebarLabel: 'Referência da CLI',
      sourcePath: 'docs/pt-br/reference/cli.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/cli.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 10,
    },
    'reference/api': {
      slug: 'reference/api',
      title: 'Referência Da API',
      sidebarLabel: 'Referência Da API',
      sourcePath: 'docs/pt-br/reference/api.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/api.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 20,
    },
    'reference/testing': {
      slug: 'reference/testing',
      title: 'Estratégia De Testes',
      sidebarLabel: 'Estratégia De Testes',
      sourcePath: 'docs/pt-br/reference/testing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/testing.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 30,
    },
    'reference/tooling': {
      slug: 'reference/tooling',
      title: 'Ferramentas',
      sidebarLabel: 'Ferramentas',
      sourcePath: 'docs/pt-br/reference/tooling.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/tooling.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 40,
    },
    'reference/agent-playbooks': {
      slug: 'reference/agent-playbooks',
      title: 'Playbooks De Agentes',
      sidebarLabel: 'Playbooks De Agentes',
      sourcePath: 'docs/pt-br/reference/agent-playbooks.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/agent-playbooks.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 50,
    },
    'reference/releasing': {
      slug: 'reference/releasing',
      title: 'Releases',
      sidebarLabel: 'Releases',
      sourcePath: 'docs/pt-br/reference/releasing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/reference/releasing.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 60,
    },
    'operations/deployment': {
      slug: 'operations/deployment',
      title: 'Deploy',
      sidebarLabel: 'Deploy',
      sourcePath: 'docs/pt-br/operations/deployment.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/operations/deployment.md',
      groupId: 'operations',
      groupTitle: 'Operações',
      order: 10,
    },
    'operations/security': {
      slug: 'operations/security',
      title: 'Política De Segurança',
      sidebarLabel: 'Política De Segurança',
      sourcePath: 'docs/pt-br/operations/security.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/pt-br/operations/security.md',
      groupId: 'operations',
      groupTitle: 'Operações',
      order: 20,
    },
  },
  en: {
    quickstart: {
      slug: 'quickstart',
      title: 'MangoStudio',
      sidebarLabel: 'Quickstart',
      sourcePath: 'README.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/README.md',
      groupId: 'getting-started',
      groupTitle: 'Getting Started',
      order: 10,
    },
    'guides/contributing': {
      slug: 'guides/contributing',
      title: 'Contributing to MangoStudio',
      sidebarLabel: 'Contributing to MangoStudio',
      sourcePath: '.github/CONTRIBUTING.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/.github/CONTRIBUTING.md',
      groupId: 'guides',
      groupTitle: 'Guides',
      order: 10,
    },
    'guides/contributor-quickstart': {
      slug: 'guides/contributor-quickstart',
      title: 'Contributor Quickstart',
      sidebarLabel: 'Contributor Quickstart',
      sourcePath: 'docs/guides/contributor-quickstart.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/guides/contributor-quickstart.md',
      groupId: 'guides',
      groupTitle: 'Guides',
      order: 20,
    },
    'features/settings': {
      slug: 'features/settings',
      title: 'Settings Architecture',
      sidebarLabel: 'Settings Architecture',
      sourcePath: 'docs/features/settings.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/settings.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 10,
    },
    'features/tools': {
      slug: 'features/tools',
      title: 'Tools System',
      sidebarLabel: 'Tools System',
      sourcePath: 'docs/features/tools.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/tools.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 20,
    },
    'features/attachments': {
      slug: 'features/attachments',
      title: 'Attachments',
      sidebarLabel: 'Attachments',
      sourcePath: 'docs/features/attachments.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/attachments.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 30,
    },
    'features/image-generation': {
      slug: 'features/image-generation',
      title: 'Image Generation',
      sidebarLabel: 'Image Generation',
      sourcePath: 'docs/features/image-generation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/features/image-generation.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 40,
    },
    'providers/development': {
      slug: 'providers/development',
      title: 'Provider Development Guide',
      sidebarLabel: 'Provider Development Guide',
      sourcePath: 'docs/providers/development.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/providers/development.md',
      groupId: 'providers',
      groupTitle: 'Providers',
      order: 10,
    },
    'providers/deepseek': {
      slug: 'providers/deepseek',
      title: 'DeepSeek Provider',
      sidebarLabel: 'DeepSeek Provider',
      sourcePath: 'docs/providers/deepseek.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/providers/deepseek.md',
      groupId: 'providers',
      groupTitle: 'Providers',
      order: 20,
    },
    'architecture/overview': {
      slug: 'architecture/overview',
      title: 'Architecture Overview',
      sidebarLabel: 'Architecture Overview',
      sourcePath: 'docs/architecture/overview.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/overview.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 10,
    },
    'architecture/streaming': {
      slug: 'architecture/streaming',
      title: 'Streaming Architecture',
      sidebarLabel: 'Streaming Architecture',
      sourcePath: 'docs/architecture/streaming.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/streaming.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 20,
    },
    'architecture/continuation': {
      slug: 'architecture/continuation',
      title: 'Continuation Architecture',
      sidebarLabel: 'Continuation Architecture',
      sourcePath: 'docs/architecture/continuation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/continuation.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 30,
    },
    'architecture/context-compaction': {
      slug: 'architecture/context-compaction',
      title: 'Context Compaction',
      sidebarLabel: 'Context Compaction',
      sourcePath: 'docs/architecture/context-compaction.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/context-compaction.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 40,
    },
    'architecture/i18n': {
      slug: 'architecture/i18n',
      title: 'Internationalization (i18n)',
      sidebarLabel: 'Internationalization (i18n)',
      sourcePath: 'docs/architecture/i18n.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/architecture/i18n.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 50,
    },
    'reference/cli': {
      slug: 'reference/cli',
      title: 'CLI Reference',
      sidebarLabel: 'CLI Reference',
      sourcePath: 'docs/reference/cli.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/cli.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 10,
    },
    'reference/api': {
      slug: 'reference/api',
      title: 'API Reference',
      sidebarLabel: 'API Reference',
      sourcePath: 'docs/reference/api.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/api.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 20,
    },
    'reference/testing': {
      slug: 'reference/testing',
      title: 'Testing Strategy',
      sidebarLabel: 'Testing Strategy',
      sourcePath: 'docs/reference/testing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/testing.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 30,
    },
    'reference/tooling': {
      slug: 'reference/tooling',
      title: 'Tooling',
      sidebarLabel: 'Tooling',
      sourcePath: 'docs/reference/tooling.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/tooling.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 40,
    },
    'reference/agent-playbooks': {
      slug: 'reference/agent-playbooks',
      title: 'Agent Playbooks',
      sidebarLabel: 'Agent Playbooks',
      sourcePath: 'docs/reference/agent-playbooks.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/agent-playbooks.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 50,
    },
    'reference/releasing': {
      slug: 'reference/releasing',
      title: 'Releasing',
      sidebarLabel: 'Releasing',
      sourcePath: 'docs/reference/releasing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/reference/releasing.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 60,
    },
    'operations/deployment': {
      slug: 'operations/deployment',
      title: 'Deployment',
      sidebarLabel: 'Deployment',
      sourcePath: 'docs/operations/deployment.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/docs/operations/deployment.md',
      groupId: 'operations',
      groupTitle: 'Operations',
      order: 10,
    },
    'operations/security': {
      slug: 'operations/security',
      title: 'Security Policy',
      sidebarLabel: 'Security Policy',
      sourcePath: '.github/SECURITY.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/c8a260ecd3cf98c5fb630b756a93afe762cb2af8/.github/SECURITY.md',
      groupId: 'operations',
      groupTitle: 'Operations',
      order: 20,
    },
  },
} as const satisfies Record<Lang, Record<string, GeneratedDocNavItem>>;
