// AUTO-GENERATED by scripts/sync-docs.ts - edit the generator, not this file.
import type { Lang } from '@/i18n/types';

export type DocGroupId =
  | 'getting-started'
  | 'guides'
  | 'features'
  | 'providers'
  | 'architecture'
  | 'reference'
  | 'operations';

export interface GeneratedDocNavItem {
  slug: string;
  title: string;
  sidebarLabel: string;
  description: string;
  sourcePath: string;
  sourceUrl: string;
  groupId: DocGroupId;
  groupTitle: string;
  order: number;
}

export interface GeneratedDocNavGroup {
  id: DocGroupId;
  title: string;
  items: GeneratedDocNavItem[];
}

export const DOCS_DEFAULT_SLUG = 'quickstart';

export const DOCS_SOURCE = {
  repo: 'https://github.com/juliopolycarpo/mangostudio',
  commit: '5490f9a050c73225da1673d7dce7f6f1300b548c',
} as const;

export const DOCS_NAV = {
  pt: [
    {
      id: 'getting-started',
      title: 'Começando',
      items: [
        {
          slug: 'quickstart',
          title: 'MangoStudio',
          sidebarLabel: 'Início rápido',
          description:
            'Estúdio de geração de imagens e chat alimentado por IA com suporte a modelos Gemini, compatíveis com OpenAI e Anthropic.',
          sourcePath: 'docs/pt-br/README.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/README.md',
          groupId: 'getting-started',
          groupTitle: 'Começando',
          order: 10,
        },
      ],
    },
    {
      id: 'guides',
      title: 'Guias',
      items: [
        {
          slug: 'guides/contributing',
          title: 'Contribuindo com o MangoStudio',
          sidebarLabel: 'Contribuindo com o MangoStudio',
          description: 'Obrigado pelo seu interesse em contribuir com o MangoStudio!',
          sourcePath: 'docs/pt-br/CONTRIBUTING.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/CONTRIBUTING.md',
          groupId: 'guides',
          groupTitle: 'Guias',
          order: 10,
        },
        {
          slug: 'guides/contributor-quickstart',
          title: 'Início Rápido Para Contribuidores',
          sidebarLabel: 'Início Rápido Para Contribuidores',
          description:
            'Use este guia quando quiser o caminho mais curto entre o clone do repositório e uma alteração validada.',
          sourcePath: 'docs/pt-br/guides/contributor-quickstart.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/guides/contributor-quickstart.md',
          groupId: 'guides',
          groupTitle: 'Guias',
          order: 20,
        },
      ],
    },
    {
      id: 'features',
      title: 'Recursos',
      items: [
        {
          slug: 'features/settings',
          title: 'Arquitetura De Settings',
          sidebarLabel: 'Arquitetura De Settings',
          description:
            'O MangoStudio tem três camadas independentes de settings, cada uma com sua própria persistência, API e módulo no frontend.',
          sourcePath: 'docs/pt-br/features/settings.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/settings.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 10,
        },
        {
          slug: 'features/tools',
          title: 'Sistema De Tools',
          sidebarLabel: 'Sistema De Tools',
          description:
            'O MangoStudio suporta tool calling agnóstico a provedor durante turnos de chat. Modelos podem chamar tools, o sistema as executa e os resultados são…',
          sourcePath: 'docs/pt-br/features/tools.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/tools.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 20,
        },
        {
          slug: 'features/attachments',
          title: 'Attachments',
          sidebarLabel: 'Attachments',
          description:
            'O MangoStudio suporta upload de arquivos como attachments de chat e sua entrega aos provedores de IA durante a geração.',
          sourcePath: 'docs/pt-br/features/attachments.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/attachments.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 30,
        },
        {
          slug: 'features/image-generation',
          title: 'Geração De Imagem',
          sidebarLabel: 'Geração De Imagem',
          description:
            'O MangoStudio suporta geração de imagem por dois caminhos: a tool generate_image, chamada por modelos durante chats de texto, e a geração direta iniciada pela…',
          sourcePath: 'docs/pt-br/features/image-generation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/image-generation.md',
          groupId: 'features',
          groupTitle: 'Recursos',
          order: 40,
        },
      ],
    },
    {
      id: 'providers',
      title: 'Provedores',
      items: [
        {
          slug: 'providers/development',
          title: 'Guia De Desenvolvimento De Provedores',
          sidebarLabel: 'Guia De Desenvolvimento De Provedores',
          description:
            'Todo provedor precisa implementar a interface AIProvider em apps/api/src/services/providers/types.ts.',
          sourcePath: 'docs/pt-br/providers/development.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/providers/development.md',
          groupId: 'providers',
          groupTitle: 'Provedores',
          order: 10,
        },
        {
          slug: 'providers/deepseek',
          title: 'Provedor DeepSeek',
          sidebarLabel: 'Provedor DeepSeek',
          description:
            'O DeepSeek é modelado como um provedor de primeira classe, e não apenas como um connector OpenAI-compatible, para expor capacidades específicas do DeepSeek…',
          sourcePath: 'docs/pt-br/providers/deepseek.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/providers/deepseek.md',
          groupId: 'providers',
          groupTitle: 'Provedores',
          order: 20,
        },
      ],
    },
    {
      id: 'architecture',
      title: 'Arquitetura',
      items: [
        {
          slug: 'architecture/overview',
          title: 'Visão Geral Da Arquitetura',
          sidebarLabel: 'Visão Geral Da Arquitetura',
          description:
            'O MangoStudio segue uma arquitetura modular inspirada em DDD distribuída em três workspaces. Este documento explica as decisões de design, as…',
          sourcePath: 'docs/pt-br/architecture/overview.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/overview.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 10,
        },
        {
          slug: 'architecture/streaming',
          title: 'Arquitetura De Streaming',
          sidebarLabel: 'Arquitetura De Streaming',
          description:
            'As respostas do chat são entregues via Server-Sent Events (SSE) sobre uma única conexão HTTP. O frontend consome o stream usando ReadableStream da Fetch API e…',
          sourcePath: 'docs/pt-br/architecture/streaming.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/streaming.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 20,
        },
        {
          slug: 'architecture/continuation',
          title: 'Arquitetura De Continuação',
          sidebarLabel: 'Arquitetura De Continuação',
          description:
            'Continuação é o mecanismo que permite a uma conversa multi-turno preservar contexto entre interações separadas do usuário sem reenviar todo o histórico do…',
          sourcePath: 'docs/pt-br/architecture/continuation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/continuation.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 30,
        },
        {
          slug: 'architecture/context-compaction',
          title: 'Compactação De Contexto',
          sidebarLabel: 'Compactação De Contexto',
          description:
            'Quando uma conversa se aproxima do limite da janela de contexto do modelo, o MangoStudio avisa o usuário e oferece opções de compactação. Este documento…',
          sourcePath: 'docs/pt-br/architecture/context-compaction.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/context-compaction.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 40,
        },
        {
          slug: 'architecture/i18n',
          title: 'Internacionalização (i18n)',
          sidebarLabel: 'Internacionalização (i18n)',
          description:
            'O MangoStudio usa um sistema de i18n em TypeScript puro com verificação de traduções em tempo de compilação.',
          sourcePath: 'docs/pt-br/architecture/i18n.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/i18n.md',
          groupId: 'architecture',
          groupTitle: 'Arquitetura',
          order: 50,
        },
      ],
    },
    {
      id: 'reference',
      title: 'Referência',
      items: [
        {
          slug: 'reference/cli',
          title: 'Referência da CLI',
          sidebarLabel: 'Referência da CLI',
          description:
            'O MangoStudio é distribuído como um binário único que também funciona como CLI para rodar e gerenciar um servidor local. Os mesmos comandos funcionam no…',
          sourcePath: 'docs/pt-br/reference/cli.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/cli.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 10,
        },
        {
          slug: 'reference/api',
          title: 'Referência Da API',
          sidebarLabel: 'Referência Da API',
          description: 'O MangoStudio expõe uma API REST em /api/ e um endpoint de streaming SSE.',
          sourcePath: 'docs/pt-br/reference/api.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/api.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 20,
        },
        {
          slug: 'reference/testing',
          title: 'Estratégia De Testes',
          sidebarLabel: 'Estratégia De Testes',
          description:
            'Este monorepo usa uma arquitetura de testes orientada a workspaces em apps/*/tests. O código de produção permanece em src/, e os testes são agrupados por…',
          sourcePath: 'docs/pt-br/reference/testing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/testing.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 30,
        },
        {
          slug: 'reference/tooling',
          title: 'Ferramentas',
          sidebarLabel: 'Ferramentas',
          description:
            'Este monorepo usa Turborepo 2.x (atualmente 2.9.16) como camada compartilhada de build system. O Turborepo orquestra a execução de tasks entre workspaces e…',
          sourcePath: 'docs/pt-br/reference/tooling.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/tooling.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 40,
        },
        {
          slug: 'reference/agent-playbooks',
          title: 'Playbooks De Agentes',
          sidebarLabel: 'Playbooks De Agentes',
          description:
            'Abra apenas a seção que corresponda à tarefa atual. Este arquivo é intencionalmente mais detalhado que AGENTS.md e deve ser usado sob demanda, não por padrão.',
          sourcePath: 'docs/pt-br/reference/agent-playbooks.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/agent-playbooks.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 50,
        },
        {
          slug: 'reference/releasing',
          title: 'Releases',
          sidebarLabel: 'Releases',
          description:
            'O MangoStudio é distribuído como binários standalone (GitHub Releases), imagem Docker no GHCR, CLI npm (mangostudio), tap Homebrew, bucket Scoop (Windows) e…',
          sourcePath: 'docs/pt-br/reference/releasing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/releasing.md',
          groupId: 'reference',
          groupTitle: 'Referência',
          order: 60,
        },
      ],
    },
    {
      id: 'operations',
      title: 'Operações',
      items: [
        {
          slug: 'operations/deployment',
          title: 'Deploy',
          sidebarLabel: 'Deploy',
          description:
            'O MangoStudio pode ser implantado como binários standalone específicos por plataforma com assets do frontend embutidos.',
          sourcePath: 'docs/pt-br/operations/deployment.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/operations/deployment.md',
          groupId: 'operations',
          groupTitle: 'Operações',
          order: 10,
        },
        {
          slug: 'operations/security',
          title: 'Política De Segurança',
          sidebarLabel: 'Política De Segurança',
          description:
            'Se você descobrir uma vulnerabilidade de segurança no MangoStudio, reporte-a de forma privada em vez de abrir uma issue pública.',
          sourcePath: 'docs/pt-br/operations/security.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/operations/security.md',
          groupId: 'operations',
          groupTitle: 'Operações',
          order: 20,
        },
      ],
    },
  ],
  en: [
    {
      id: 'getting-started',
      title: 'Getting Started',
      items: [
        {
          slug: 'quickstart',
          title: 'MangoStudio',
          sidebarLabel: 'Quickstart',
          description:
            'AI-powered image generation and chat studio supporting Gemini, OpenAI-compatible, and Anthropic models.',
          sourcePath: 'README.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/README.md',
          groupId: 'getting-started',
          groupTitle: 'Getting Started',
          order: 10,
        },
      ],
    },
    {
      id: 'guides',
      title: 'Guides',
      items: [
        {
          slug: 'guides/contributing',
          title: 'Contributing to MangoStudio',
          sidebarLabel: 'Contributing to MangoStudio',
          description: 'Thank you for your interest in contributing to MangoStudio!',
          sourcePath: '.github/CONTRIBUTING.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/.github/CONTRIBUTING.md',
          groupId: 'guides',
          groupTitle: 'Guides',
          order: 10,
        },
        {
          slug: 'guides/contributor-quickstart',
          title: 'Contributor Quickstart',
          sidebarLabel: 'Contributor Quickstart',
          description:
            'Use this guide when you want the shortest path from clone to a validated change.',
          sourcePath: 'docs/guides/contributor-quickstart.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/guides/contributor-quickstart.md',
          groupId: 'guides',
          groupTitle: 'Guides',
          order: 20,
        },
      ],
    },
    {
      id: 'features',
      title: 'Features',
      items: [
        {
          slug: 'features/settings',
          title: 'Settings Architecture',
          sidebarLabel: 'Settings Architecture',
          description:
            'MangoStudio has three independent settings layers, each with its own persistence, API, and frontend module.',
          sourcePath: 'docs/features/settings.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/settings.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 10,
        },
        {
          slug: 'features/tools',
          title: 'Tools System',
          sidebarLabel: 'Tools System',
          description:
            'MangoStudio supports provider-agnostic tool calling during chat turns. Models can call tools, the system executes them, and results are fed back to the model…',
          sourcePath: 'docs/features/tools.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/tools.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 20,
        },
        {
          slug: 'features/attachments',
          title: 'Attachments',
          sidebarLabel: 'Attachments',
          description:
            'MangoStudio supports uploading files as chat attachments and delivering them to AI providers during generation.',
          sourcePath: 'docs/features/attachments.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/attachments.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 30,
        },
        {
          slug: 'features/image-generation',
          title: 'Image Generation',
          sidebarLabel: 'Image Generation',
          description:
            'MangoStudio supports image generation through two paths: the generate_image tool (called by models during text chats) and direct generation from the UI.',
          sourcePath: 'docs/features/image-generation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/image-generation.md',
          groupId: 'features',
          groupTitle: 'Features',
          order: 40,
        },
      ],
    },
    {
      id: 'providers',
      title: 'Providers',
      items: [
        {
          slug: 'providers/development',
          title: 'Provider Development Guide',
          sidebarLabel: 'Provider Development Guide',
          description:
            'Every provider must implement the AIProvider interface (apps/api/src/services/providers/types.ts).',
          sourcePath: 'docs/providers/development.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/providers/development.md',
          groupId: 'providers',
          groupTitle: 'Providers',
          order: 10,
        },
        {
          slug: 'providers/deepseek',
          title: 'DeepSeek Provider',
          sidebarLabel: 'DeepSeek Provider',
          description:
            'DeepSeek is modeled as a first-class provider (not just an OpenAI-compatible connector) to surface DeepSeek-specific capabilities: reasoning tokens, prefix…',
          sourcePath: 'docs/providers/deepseek.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/providers/deepseek.md',
          groupId: 'providers',
          groupTitle: 'Providers',
          order: 20,
        },
      ],
    },
    {
      id: 'architecture',
      title: 'Architecture',
      items: [
        {
          slug: 'architecture/overview',
          title: 'Architecture Overview',
          sidebarLabel: 'Architecture Overview',
          description:
            'MangoStudio follows a modular DDD-inspired architecture across three workspaces. This document explains the design decisions, layer responsibilities, and data…',
          sourcePath: 'docs/architecture/overview.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/overview.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 10,
        },
        {
          slug: 'architecture/streaming',
          title: 'Streaming Architecture',
          sidebarLabel: 'Streaming Architecture',
          description:
            "Chat responses are delivered via Server-Sent Events (SSE) over a single HTTP connection. The frontend consumes the stream using the Fetch API's ReadableStream…",
          sourcePath: 'docs/architecture/streaming.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/streaming.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 20,
        },
        {
          slug: 'architecture/continuation',
          title: 'Continuation Architecture',
          sidebarLabel: 'Continuation Architecture',
          description:
            'Continuation is the mechanism that lets a multi-turn conversation preserve context across separate user interactions without resending the entire chat history…',
          sourcePath: 'docs/architecture/continuation.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/continuation.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 30,
        },
        {
          slug: 'architecture/context-compaction',
          title: 'Context Compaction',
          sidebarLabel: 'Context Compaction',
          description:
            "When a conversation approaches the model's context window limit, MangoStudio warns the user and offers compaction options. This document explains the snapshot…",
          sourcePath: 'docs/architecture/context-compaction.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/context-compaction.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 40,
        },
        {
          slug: 'architecture/i18n',
          title: 'Internationalization (i18n)',
          sidebarLabel: 'Internationalization (i18n)',
          description:
            'MangoStudio uses a pure TypeScript i18n system with compile-time translation verification.',
          sourcePath: 'docs/architecture/i18n.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/i18n.md',
          groupId: 'architecture',
          groupTitle: 'Architecture',
          order: 50,
        },
      ],
    },
    {
      id: 'reference',
      title: 'Reference',
      items: [
        {
          slug: 'reference/cli',
          title: 'CLI Reference',
          sidebarLabel: 'CLI Reference',
          description:
            'MangoStudio ships as a single binary that doubles as a CLI for running and managing one local server. The same commands work from the installed binary…',
          sourcePath: 'docs/reference/cli.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/cli.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 10,
        },
        {
          slug: 'reference/api',
          title: 'API Reference',
          sidebarLabel: 'API Reference',
          description: 'MangoStudio exposes a REST API under /api/ and an SSE streaming endpoint.',
          sourcePath: 'docs/reference/api.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/api.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 20,
        },
        {
          slug: 'reference/testing',
          title: 'Testing Strategy',
          sidebarLabel: 'Testing Strategy',
          description:
            'This monorepo uses a workspace-first testing architecture under apps/*/tests. Production code stays in src/, and tests are grouped by intent as unit or…',
          sourcePath: 'docs/reference/testing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/testing.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 30,
        },
        {
          slug: 'reference/tooling',
          title: 'Tooling',
          sidebarLabel: 'Tooling',
          description:
            'This monorepo uses Turborepo 2.x (currently 2.9.16) as its shared build-system layer. Turborepo orchestrates task execution across workspaces and provides a…',
          sourcePath: 'docs/reference/tooling.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/tooling.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 40,
        },
        {
          slug: 'reference/agent-playbooks',
          title: 'Agent Playbooks',
          sidebarLabel: 'Agent Playbooks',
          description:
            'Open only the section that matches the current task. This file is intentionally more detailed than AGENTS.md and should be used on demand, not by default.',
          sourcePath: 'docs/reference/agent-playbooks.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/agent-playbooks.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 50,
        },
        {
          slug: 'reference/releasing',
          title: 'Releasing',
          sidebarLabel: 'Releasing',
          description:
            'MangoStudio ships as standalone binaries (GitHub Releases), as a Docker image on GHCR, as an npm CLI (mangostudio), via a Homebrew tap, via a Scoop bucket…',
          sourcePath: 'docs/reference/releasing.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/releasing.md',
          groupId: 'reference',
          groupTitle: 'Reference',
          order: 60,
        },
      ],
    },
    {
      id: 'operations',
      title: 'Operations',
      items: [
        {
          slug: 'operations/deployment',
          title: 'Deployment',
          sidebarLabel: 'Deployment',
          description:
            'MangoStudio can be deployed as standalone platform-specific binaries with embedded frontend assets.',
          sourcePath: 'docs/operations/deployment.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/operations/deployment.md',
          groupId: 'operations',
          groupTitle: 'Operations',
          order: 10,
        },
        {
          slug: 'operations/security',
          title: 'Security Policy',
          sidebarLabel: 'Security Policy',
          description:
            'If you discover a security vulnerability in MangoStudio, please report it privately rather than opening a public issue.',
          sourcePath: '.github/SECURITY.md',
          sourceUrl:
            'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/.github/SECURITY.md',
          groupId: 'operations',
          groupTitle: 'Operations',
          order: 20,
        },
      ],
    },
  ],
} as const satisfies Record<Lang, readonly GeneratedDocNavGroup[]>;

export const DOCS_BY_SLUG = {
  pt: {
    quickstart: {
      slug: 'quickstart',
      title: 'MangoStudio',
      sidebarLabel: 'Início rápido',
      description:
        'Estúdio de geração de imagens e chat alimentado por IA com suporte a modelos Gemini, compatíveis com OpenAI e Anthropic.',
      sourcePath: 'docs/pt-br/README.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/README.md',
      groupId: 'getting-started',
      groupTitle: 'Começando',
      order: 10,
    },
    'guides/contributing': {
      slug: 'guides/contributing',
      title: 'Contribuindo com o MangoStudio',
      sidebarLabel: 'Contribuindo com o MangoStudio',
      description: 'Obrigado pelo seu interesse em contribuir com o MangoStudio!',
      sourcePath: 'docs/pt-br/CONTRIBUTING.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/CONTRIBUTING.md',
      groupId: 'guides',
      groupTitle: 'Guias',
      order: 10,
    },
    'guides/contributor-quickstart': {
      slug: 'guides/contributor-quickstart',
      title: 'Início Rápido Para Contribuidores',
      sidebarLabel: 'Início Rápido Para Contribuidores',
      description:
        'Use este guia quando quiser o caminho mais curto entre o clone do repositório e uma alteração validada.',
      sourcePath: 'docs/pt-br/guides/contributor-quickstart.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/guides/contributor-quickstart.md',
      groupId: 'guides',
      groupTitle: 'Guias',
      order: 20,
    },
    'features/settings': {
      slug: 'features/settings',
      title: 'Arquitetura De Settings',
      sidebarLabel: 'Arquitetura De Settings',
      description:
        'O MangoStudio tem três camadas independentes de settings, cada uma com sua própria persistência, API e módulo no frontend.',
      sourcePath: 'docs/pt-br/features/settings.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/settings.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 10,
    },
    'features/tools': {
      slug: 'features/tools',
      title: 'Sistema De Tools',
      sidebarLabel: 'Sistema De Tools',
      description:
        'O MangoStudio suporta tool calling agnóstico a provedor durante turnos de chat. Modelos podem chamar tools, o sistema as executa e os resultados são…',
      sourcePath: 'docs/pt-br/features/tools.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/tools.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 20,
    },
    'features/attachments': {
      slug: 'features/attachments',
      title: 'Attachments',
      sidebarLabel: 'Attachments',
      description:
        'O MangoStudio suporta upload de arquivos como attachments de chat e sua entrega aos provedores de IA durante a geração.',
      sourcePath: 'docs/pt-br/features/attachments.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/attachments.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 30,
    },
    'features/image-generation': {
      slug: 'features/image-generation',
      title: 'Geração De Imagem',
      sidebarLabel: 'Geração De Imagem',
      description:
        'O MangoStudio suporta geração de imagem por dois caminhos: a tool generate_image, chamada por modelos durante chats de texto, e a geração direta iniciada pela…',
      sourcePath: 'docs/pt-br/features/image-generation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/features/image-generation.md',
      groupId: 'features',
      groupTitle: 'Recursos',
      order: 40,
    },
    'providers/development': {
      slug: 'providers/development',
      title: 'Guia De Desenvolvimento De Provedores',
      sidebarLabel: 'Guia De Desenvolvimento De Provedores',
      description:
        'Todo provedor precisa implementar a interface AIProvider em apps/api/src/services/providers/types.ts.',
      sourcePath: 'docs/pt-br/providers/development.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/providers/development.md',
      groupId: 'providers',
      groupTitle: 'Provedores',
      order: 10,
    },
    'providers/deepseek': {
      slug: 'providers/deepseek',
      title: 'Provedor DeepSeek',
      sidebarLabel: 'Provedor DeepSeek',
      description:
        'O DeepSeek é modelado como um provedor de primeira classe, e não apenas como um connector OpenAI-compatible, para expor capacidades específicas do DeepSeek…',
      sourcePath: 'docs/pt-br/providers/deepseek.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/providers/deepseek.md',
      groupId: 'providers',
      groupTitle: 'Provedores',
      order: 20,
    },
    'architecture/overview': {
      slug: 'architecture/overview',
      title: 'Visão Geral Da Arquitetura',
      sidebarLabel: 'Visão Geral Da Arquitetura',
      description:
        'O MangoStudio segue uma arquitetura modular inspirada em DDD distribuída em três workspaces. Este documento explica as decisões de design, as…',
      sourcePath: 'docs/pt-br/architecture/overview.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/overview.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 10,
    },
    'architecture/streaming': {
      slug: 'architecture/streaming',
      title: 'Arquitetura De Streaming',
      sidebarLabel: 'Arquitetura De Streaming',
      description:
        'As respostas do chat são entregues via Server-Sent Events (SSE) sobre uma única conexão HTTP. O frontend consome o stream usando ReadableStream da Fetch API e…',
      sourcePath: 'docs/pt-br/architecture/streaming.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/streaming.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 20,
    },
    'architecture/continuation': {
      slug: 'architecture/continuation',
      title: 'Arquitetura De Continuação',
      sidebarLabel: 'Arquitetura De Continuação',
      description:
        'Continuação é o mecanismo que permite a uma conversa multi-turno preservar contexto entre interações separadas do usuário sem reenviar todo o histórico do…',
      sourcePath: 'docs/pt-br/architecture/continuation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/continuation.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 30,
    },
    'architecture/context-compaction': {
      slug: 'architecture/context-compaction',
      title: 'Compactação De Contexto',
      sidebarLabel: 'Compactação De Contexto',
      description:
        'Quando uma conversa se aproxima do limite da janela de contexto do modelo, o MangoStudio avisa o usuário e oferece opções de compactação. Este documento…',
      sourcePath: 'docs/pt-br/architecture/context-compaction.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/context-compaction.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 40,
    },
    'architecture/i18n': {
      slug: 'architecture/i18n',
      title: 'Internacionalização (i18n)',
      sidebarLabel: 'Internacionalização (i18n)',
      description:
        'O MangoStudio usa um sistema de i18n em TypeScript puro com verificação de traduções em tempo de compilação.',
      sourcePath: 'docs/pt-br/architecture/i18n.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/architecture/i18n.md',
      groupId: 'architecture',
      groupTitle: 'Arquitetura',
      order: 50,
    },
    'reference/cli': {
      slug: 'reference/cli',
      title: 'Referência da CLI',
      sidebarLabel: 'Referência da CLI',
      description:
        'O MangoStudio é distribuído como um binário único que também funciona como CLI para rodar e gerenciar um servidor local. Os mesmos comandos funcionam no…',
      sourcePath: 'docs/pt-br/reference/cli.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/cli.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 10,
    },
    'reference/api': {
      slug: 'reference/api',
      title: 'Referência Da API',
      sidebarLabel: 'Referência Da API',
      description: 'O MangoStudio expõe uma API REST em /api/ e um endpoint de streaming SSE.',
      sourcePath: 'docs/pt-br/reference/api.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/api.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 20,
    },
    'reference/testing': {
      slug: 'reference/testing',
      title: 'Estratégia De Testes',
      sidebarLabel: 'Estratégia De Testes',
      description:
        'Este monorepo usa uma arquitetura de testes orientada a workspaces em apps/*/tests. O código de produção permanece em src/, e os testes são agrupados por…',
      sourcePath: 'docs/pt-br/reference/testing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/testing.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 30,
    },
    'reference/tooling': {
      slug: 'reference/tooling',
      title: 'Ferramentas',
      sidebarLabel: 'Ferramentas',
      description:
        'Este monorepo usa Turborepo 2.x (atualmente 2.9.16) como camada compartilhada de build system. O Turborepo orquestra a execução de tasks entre workspaces e…',
      sourcePath: 'docs/pt-br/reference/tooling.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/tooling.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 40,
    },
    'reference/agent-playbooks': {
      slug: 'reference/agent-playbooks',
      title: 'Playbooks De Agentes',
      sidebarLabel: 'Playbooks De Agentes',
      description:
        'Abra apenas a seção que corresponda à tarefa atual. Este arquivo é intencionalmente mais detalhado que AGENTS.md e deve ser usado sob demanda, não por padrão.',
      sourcePath: 'docs/pt-br/reference/agent-playbooks.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/agent-playbooks.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 50,
    },
    'reference/releasing': {
      slug: 'reference/releasing',
      title: 'Releases',
      sidebarLabel: 'Releases',
      description:
        'O MangoStudio é distribuído como binários standalone (GitHub Releases), imagem Docker no GHCR, CLI npm (mangostudio), tap Homebrew, bucket Scoop (Windows) e…',
      sourcePath: 'docs/pt-br/reference/releasing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/reference/releasing.md',
      groupId: 'reference',
      groupTitle: 'Referência',
      order: 60,
    },
    'operations/deployment': {
      slug: 'operations/deployment',
      title: 'Deploy',
      sidebarLabel: 'Deploy',
      description:
        'O MangoStudio pode ser implantado como binários standalone específicos por plataforma com assets do frontend embutidos.',
      sourcePath: 'docs/pt-br/operations/deployment.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/operations/deployment.md',
      groupId: 'operations',
      groupTitle: 'Operações',
      order: 10,
    },
    'operations/security': {
      slug: 'operations/security',
      title: 'Política De Segurança',
      sidebarLabel: 'Política De Segurança',
      description:
        'Se você descobrir uma vulnerabilidade de segurança no MangoStudio, reporte-a de forma privada em vez de abrir uma issue pública.',
      sourcePath: 'docs/pt-br/operations/security.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/pt-br/operations/security.md',
      groupId: 'operations',
      groupTitle: 'Operações',
      order: 20,
    },
  },
  en: {
    quickstart: {
      slug: 'quickstart',
      title: 'MangoStudio',
      sidebarLabel: 'Quickstart',
      description:
        'AI-powered image generation and chat studio supporting Gemini, OpenAI-compatible, and Anthropic models.',
      sourcePath: 'README.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/README.md',
      groupId: 'getting-started',
      groupTitle: 'Getting Started',
      order: 10,
    },
    'guides/contributing': {
      slug: 'guides/contributing',
      title: 'Contributing to MangoStudio',
      sidebarLabel: 'Contributing to MangoStudio',
      description: 'Thank you for your interest in contributing to MangoStudio!',
      sourcePath: '.github/CONTRIBUTING.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/.github/CONTRIBUTING.md',
      groupId: 'guides',
      groupTitle: 'Guides',
      order: 10,
    },
    'guides/contributor-quickstart': {
      slug: 'guides/contributor-quickstart',
      title: 'Contributor Quickstart',
      sidebarLabel: 'Contributor Quickstart',
      description:
        'Use this guide when you want the shortest path from clone to a validated change.',
      sourcePath: 'docs/guides/contributor-quickstart.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/guides/contributor-quickstart.md',
      groupId: 'guides',
      groupTitle: 'Guides',
      order: 20,
    },
    'features/settings': {
      slug: 'features/settings',
      title: 'Settings Architecture',
      sidebarLabel: 'Settings Architecture',
      description:
        'MangoStudio has three independent settings layers, each with its own persistence, API, and frontend module.',
      sourcePath: 'docs/features/settings.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/settings.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 10,
    },
    'features/tools': {
      slug: 'features/tools',
      title: 'Tools System',
      sidebarLabel: 'Tools System',
      description:
        'MangoStudio supports provider-agnostic tool calling during chat turns. Models can call tools, the system executes them, and results are fed back to the model…',
      sourcePath: 'docs/features/tools.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/tools.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 20,
    },
    'features/attachments': {
      slug: 'features/attachments',
      title: 'Attachments',
      sidebarLabel: 'Attachments',
      description:
        'MangoStudio supports uploading files as chat attachments and delivering them to AI providers during generation.',
      sourcePath: 'docs/features/attachments.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/attachments.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 30,
    },
    'features/image-generation': {
      slug: 'features/image-generation',
      title: 'Image Generation',
      sidebarLabel: 'Image Generation',
      description:
        'MangoStudio supports image generation through two paths: the generate_image tool (called by models during text chats) and direct generation from the UI.',
      sourcePath: 'docs/features/image-generation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/features/image-generation.md',
      groupId: 'features',
      groupTitle: 'Features',
      order: 40,
    },
    'providers/development': {
      slug: 'providers/development',
      title: 'Provider Development Guide',
      sidebarLabel: 'Provider Development Guide',
      description:
        'Every provider must implement the AIProvider interface (apps/api/src/services/providers/types.ts).',
      sourcePath: 'docs/providers/development.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/providers/development.md',
      groupId: 'providers',
      groupTitle: 'Providers',
      order: 10,
    },
    'providers/deepseek': {
      slug: 'providers/deepseek',
      title: 'DeepSeek Provider',
      sidebarLabel: 'DeepSeek Provider',
      description:
        'DeepSeek is modeled as a first-class provider (not just an OpenAI-compatible connector) to surface DeepSeek-specific capabilities: reasoning tokens, prefix…',
      sourcePath: 'docs/providers/deepseek.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/providers/deepseek.md',
      groupId: 'providers',
      groupTitle: 'Providers',
      order: 20,
    },
    'architecture/overview': {
      slug: 'architecture/overview',
      title: 'Architecture Overview',
      sidebarLabel: 'Architecture Overview',
      description:
        'MangoStudio follows a modular DDD-inspired architecture across three workspaces. This document explains the design decisions, layer responsibilities, and data…',
      sourcePath: 'docs/architecture/overview.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/overview.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 10,
    },
    'architecture/streaming': {
      slug: 'architecture/streaming',
      title: 'Streaming Architecture',
      sidebarLabel: 'Streaming Architecture',
      description:
        "Chat responses are delivered via Server-Sent Events (SSE) over a single HTTP connection. The frontend consumes the stream using the Fetch API's ReadableStream…",
      sourcePath: 'docs/architecture/streaming.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/streaming.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 20,
    },
    'architecture/continuation': {
      slug: 'architecture/continuation',
      title: 'Continuation Architecture',
      sidebarLabel: 'Continuation Architecture',
      description:
        'Continuation is the mechanism that lets a multi-turn conversation preserve context across separate user interactions without resending the entire chat history…',
      sourcePath: 'docs/architecture/continuation.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/continuation.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 30,
    },
    'architecture/context-compaction': {
      slug: 'architecture/context-compaction',
      title: 'Context Compaction',
      sidebarLabel: 'Context Compaction',
      description:
        "When a conversation approaches the model's context window limit, MangoStudio warns the user and offers compaction options. This document explains the snapshot…",
      sourcePath: 'docs/architecture/context-compaction.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/context-compaction.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 40,
    },
    'architecture/i18n': {
      slug: 'architecture/i18n',
      title: 'Internationalization (i18n)',
      sidebarLabel: 'Internationalization (i18n)',
      description:
        'MangoStudio uses a pure TypeScript i18n system with compile-time translation verification.',
      sourcePath: 'docs/architecture/i18n.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/architecture/i18n.md',
      groupId: 'architecture',
      groupTitle: 'Architecture',
      order: 50,
    },
    'reference/cli': {
      slug: 'reference/cli',
      title: 'CLI Reference',
      sidebarLabel: 'CLI Reference',
      description:
        'MangoStudio ships as a single binary that doubles as a CLI for running and managing one local server. The same commands work from the installed binary…',
      sourcePath: 'docs/reference/cli.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/cli.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 10,
    },
    'reference/api': {
      slug: 'reference/api',
      title: 'API Reference',
      sidebarLabel: 'API Reference',
      description: 'MangoStudio exposes a REST API under /api/ and an SSE streaming endpoint.',
      sourcePath: 'docs/reference/api.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/api.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 20,
    },
    'reference/testing': {
      slug: 'reference/testing',
      title: 'Testing Strategy',
      sidebarLabel: 'Testing Strategy',
      description:
        'This monorepo uses a workspace-first testing architecture under apps/*/tests. Production code stays in src/, and tests are grouped by intent as unit or…',
      sourcePath: 'docs/reference/testing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/testing.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 30,
    },
    'reference/tooling': {
      slug: 'reference/tooling',
      title: 'Tooling',
      sidebarLabel: 'Tooling',
      description:
        'This monorepo uses Turborepo 2.x (currently 2.9.16) as its shared build-system layer. Turborepo orchestrates task execution across workspaces and provides a…',
      sourcePath: 'docs/reference/tooling.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/tooling.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 40,
    },
    'reference/agent-playbooks': {
      slug: 'reference/agent-playbooks',
      title: 'Agent Playbooks',
      sidebarLabel: 'Agent Playbooks',
      description:
        'Open only the section that matches the current task. This file is intentionally more detailed than AGENTS.md and should be used on demand, not by default.',
      sourcePath: 'docs/reference/agent-playbooks.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/agent-playbooks.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 50,
    },
    'reference/releasing': {
      slug: 'reference/releasing',
      title: 'Releasing',
      sidebarLabel: 'Releasing',
      description:
        'MangoStudio ships as standalone binaries (GitHub Releases), as a Docker image on GHCR, as an npm CLI (mangostudio), via a Homebrew tap, via a Scoop bucket…',
      sourcePath: 'docs/reference/releasing.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/reference/releasing.md',
      groupId: 'reference',
      groupTitle: 'Reference',
      order: 60,
    },
    'operations/deployment': {
      slug: 'operations/deployment',
      title: 'Deployment',
      sidebarLabel: 'Deployment',
      description:
        'MangoStudio can be deployed as standalone platform-specific binaries with embedded frontend assets.',
      sourcePath: 'docs/operations/deployment.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/docs/operations/deployment.md',
      groupId: 'operations',
      groupTitle: 'Operations',
      order: 10,
    },
    'operations/security': {
      slug: 'operations/security',
      title: 'Security Policy',
      sidebarLabel: 'Security Policy',
      description:
        'If you discover a security vulnerability in MangoStudio, please report it privately rather than opening a public issue.',
      sourcePath: '.github/SECURITY.md',
      sourceUrl:
        'https://github.com/juliopolycarpo/mangostudio/blob/5490f9a050c73225da1673d7dce7f6f1300b548c/.github/SECURITY.md',
      groupId: 'operations',
      groupTitle: 'Operations',
      order: 20,
    },
  },
} as const satisfies Record<Lang, Record<string, GeneratedDocNavItem>>;
