// AUTO-GENERATED by scripts/sync-releases.ts - edit the generator, not this file.
export interface GeneratedRelease {
  version: string;
  releaseDate: string;
  installCmd: string;
  source: string;
}

export const RELEASE: GeneratedRelease = {
  version: 'v0.1.0-canary.b7be89c',
  releaseDate: '2026-06-23',
  installCmd: 'bun add -g mangostudio',
  source: 'https://www.npmjs.com/package/mangostudio',
};
