// AUTO-GENERATED by scripts/sync-releases.ts - edit the generator, not this file.
export interface GeneratedRelease {
  version: string;
  releaseDate: string;
  installCmd: string;
  source: string;
}

export const RELEASE: GeneratedRelease = {
  version: 'v0.1.0',
  releaseDate: '2026-06-30',
  installCmd: 'bun add -g mangostudio',
  source: 'https://github.com/juliopolycarpo/mangostudio/releases/tag/v0.1.0',
};
